# Welcome to Jekyll!
#

# Site settings
title: W.A.R.P. Labs
description:
owner: W.A.R.P. Laboratories
first_published: 2017
email: charlie@warplabs.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://warplabs.io" # the base hostname & protocol for your site
tiles-source: posts
tiles-count: 3
social:
#  twitter: https://twitter.com/<username>
  github: https://github.com/warplaboratories
#  linkedin-square: https://linkedin.com/in/<username>
#  facebook-official: https://facebook.com/<username>
#  google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:charlie@warplabs.io
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
